[workspace]
members = [
    "servidiot-primitives",
    "servidiot-anvil",
    "servidiot-yggdrasil",
    "servidiot-network",
    "servidiot-ecs",
    "servidiot-utils", 
    "servidiot-testaround", 
    "servidiot-core", 
    "servidiot-world"]
resolver = "2"

